### PR TITLE
mod/reengagement: convert emails to use messaging system

### PR DESCRIPTION
**Pull request by bynare**

### CODE REVIEW

**Comment by bynare** [comment]
Would be good if someone could give this another quick test ;)

**Comment by danmarsden** [comment]
looks like passing stdClass object to message_send is deprecated and planned for removal in 3.6?
https://github.com/catalyst/moodle-mod_reengagement/pull/35/commits/a8b0b6fcf6c02841061f3f440c63a8619526d18c#diff-828043dc9f8d10ccd58ff8b96297794fR541

looks like more info in: https://tracker.moodle.org/browse/MDL-47162

**Comment by danmarsden** [comment]
I think it's supposed to be: 
$eventdata = new \core\message\message();

**Comment by bynare** [comment]
i'll take a look at updating the calls

**Comment by bynare** [comment]
There you go @dan ;)

Have another test and let me know if you find any other issues.

**Comment by danmarsden** [comment]
sweet - I've merged into master - will cherry-pick into other branches.

**Comment by danmarsden** [comment]
have cherry-picked back to Moodle 3.2 branch and have created a new Totara 10 branch with the same commits. I haven't backported to Moodle 3.1 branch or Totara 9 branch because the change to require core/message/message class isn't in the older releases. If you think we need to backport further we might need to copy your old code that used stdclass() instead?

**Comment by bynare** [comment]
Nah I think it's good like that for now - thanks @danmarsden !

**Pull request merged**
