### PR TITLE
Copying reengagement activity does not copy third-party settings

### PR DESCRIPTION
**Pull request by mfw-tn**
When a reengagement activity is copied via any method (duplicating the activity, copying a course with the activity, or importing the activity from a different course), the third-party settings are not copied over. Specifically, the Third-party recipients, Notification subject (Third-party), and Notification content (Third-party). 
This is my first pull request so apologies for any mistakes. We are using Moodle 3.9 if that matters. Thanks!

### CODE REVIEW

**Comment by danmarsden** [comment]
yeah - looks like you've just tried to merge the full MOODLE_311_STABLE branch into the 3.9 branch which won't work as the 3.11 branch contains a number of things that only work in newer versions - like the new user field api etc. If it's working in the newer releases you'd need to file a PR to backport the specific change - not the full branch merge. If it's not working in the newer releases - you'd need to fix it there first, then backport to the older ones - thanks!

**Comment by mfw-tn** [comment]
Thanks, sorry if I did it wrong. I saw another user submit a note with the same issue: https://github.com/catalyst/moodle-mod_reengagement/issues/81 and you'd said to submit a pull request, but I'm sorry if I misinterpreted that. I just wanted to report that we are also experiencing this bug and were hoping it would be fixed when possible. Thanks!

**Comment by danmarsden** [comment]
no worries - you'd need to find a developer that understands git if you wanted to submit a PR - if you don't have those capabilities internally you'll just need to wait for someone else to do it or until you upgrade to a newer release - thanks!

**Comment by mfw-tn** [comment]
Good to know. Was that issue resolved in a version after 3.9?

**Comment by danmarsden** [comment]
remindercount should be fixed in newer versions, but issue #81 is still open and is still an issue that requires a developer to fix.

**Pull request closed without merging**
